sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 252240

  alioss:
    access-key-id: LTAI5tLJF8h79rs8VL4ZuLEy
    access-key-secret: fVHBR3dYxCp5ywh4p8l94RiBOor6Os
    bucket-name: learn-sky-take-out
    endpoint: oss-cn-nanjing.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    password: 252240
    database: 10
    #微信配置

  wechat:
    appid: wxab383e67498169a0
    secret: 715ee6428a30ebf66d4920b30c8c3f8e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php
