sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 252240

  alioss:
    access-key-id: LTAI5tLJF8h79rs8VL4ZuLEy
    access-key-secret: fVHBR3dYxCp5ywh4p8l94RiBOor6Os
    bucket-name: learn-sky-take-out
    endpoint: oss-cn-nanjing.aliyuncs.com

  redis:
    host: localhost
    port: 6379
    password: 252240
    database: 10
    #微信配置

  wechat:
    appid: wxab383e67498169a0
    secret: 715ee6428a30ebf66d4920b30c8c3f8e
